[package]
name = "oku-core"
version = "0.1.0"
edition = "2021"
authors = ["Emil Sayahi <limesayahi@gmail.com>"]
description = "A distributed file system for use with the Oku browser."
readme = "README.md"
repository = "https://github.com/emmyoh/oku/"
documentation = "https://emmyoh.github.io/oku/oku_core/"
license = "AGPL-3.0-or-later"
default-run = "oku-core"
resolver = "3"

[lib]
name = "oku_core"
path = "src/lib.rs"
# crate-type=["rlib", "dylib", "staticlib"]

[[bin]]
name = "oku-core"
path = "src/cli/mod.rs"
doc = false
required-features = ["cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.12.1"
clap = { version = "4.6.7", features = ["derive"], optional = true }
futures = "0.3.34"
iroh = { version = "1.2.0", features = [
    "default"
] }
iroh-docs = { version = "0.101.0", features = ["default"] }
iroh-base = "1.2.0"
iroh-blobs = { version = "0.103.0", features = ["fs-store"] }
iroh-gossip = "0.101.0"
iroh-mainline-address-lookup = "0.5.0"
iroh-mdns-address-lookup = "0.5.0"
iroh-tickets = "1.0.0"
libc = { version = "0.2.189", optional = true }
mainline = { version = "8.0.0", features = ["async"] }
miette = { version = "7.6.0", features = ["fancy"] }
path-clean = "1.0.1"
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["signal"] }
env_logger = { version = "0.11.11", optional = true }
log = "0.4.34"
bs58 = "0.5.1"
anyhow = "1.0.104"
native_db = "0.8.2"
native_model = "0.4.20"
serde = "1.0.229"
toml = "1.1.6"
rayon = "1.12.0"
url = { version = "2.5.8", features = ["serde"] }
tantivy = "0.26.2"
# zebra = { git = "https://github.com/emmyoh/zebra", version = "0.1.0", features = [
#     "default_db",
# ] }
# zebra = { path = "/home/emil/Documents/GitHub/zebra", version = "0.1.0", features = [
#     "default_db",
# ] }
data-encoding = "2.11.1"
hex = "0.4.3"
jiff = { version = "0.2.37", optional = true }
dashmap = { version = "6.2.1", features = ["inline", "rayon", "serde"] }
# tree_magic_mini = { version = "3.2.2", features = ["with-gpl-data"] }
serde_json = "1.0.151"
# easy_fuser = { git = "https://github.com/Alogani/easy_fuser", rev = "2be710342ee27c1058b4be9b5e00ab09929c9e02", features = ["async"], optional = true }
# easy_fuser = { path = "/home/emil/Documents/GitHub/easy_fuser", features = ["async"], optional = true }
easy_fuser = { git = "https://github.com/emmyoh/easy_fuser", features = ["async"], optional = true }
debug-ignore = { version = "1.0.5", optional = true }
humantime = { version = "2.4.0", optional = true }
async-trait = "0.1.92"
tempfile = "3.27.0"
moka = { version = "0.12.16", features = ["future", "logging"] }

[features]
default = []
persistent = []
fuse = ["dep:libc", "dep:easy_fuser", "dep:jiff", "dep:debug-ignore"]
cli = ["dep:clap", "dep:env_logger", "dep:jiff", "dep:humantime"]
