on: push
name: Annotate code
jobs:
  clippy_check:
    name: Annotate code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install development dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev > /dev/null
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features