on:
  push:
    branches:    
        - master

name: Revise codebase

jobs:
  code_fix:
    name: Revise codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: clippy, rustfmt
      - name: Revise code files
        uses: actions-rs/cargo@v1
        with:
          command: fix
          args: --edition --edition-idioms
      - name: Commit changes to code, if any
        run: |
          git config --global user.name 'Oku'
          git config --global user.email 'OkuBrowser@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatically apply compiler suggestions"
          git push