on:
  push:
    branches: [master]
  pull_request:
name: 'Package: Flatpak for GNU + Linux (x86_64)'
jobs:
  flatpak-builder:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v3
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        default: true
        profile: minimal
    - name: Prepare for building
      run: |
        sudo dnf -q -y install gcc gcc-c++ gtk4 gtk4-devel clutter-devel libgda-devel gobject-introspection-devel nghttp2 gnutls openssl openssl-devel perl-JSON-PP git-all cmake meson ninja-build ruby > /dev/null
        ./build-dependencies.sh
        cargo update
        curl -s https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/cargo/flatpak-cargo-generator.py --output flatpak-cargo-generator.py > /dev/null
        pip3 install --user --upgrade --quiet setuptools
        pip3 install --user --quiet siphash toml aiohttp
        python3 ./flatpak-cargo-generator.py ./Cargo.lock -o ./build-aux/cargo-sources.json
        cp -avr ./data/hicolor /usr/share/icons/hicolor
    - name: Build & package Oku
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v5
      with:
        bundle: "oku.flatpak"
        manifest-path: "build-aux/io.github.OkuBrowser.oku.json"
