name: Publish documentation to GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Publish documentation"
    steps:
    - name: Install development dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev > /dev/null
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        default: true
        profile: default
    - name: Checkout codebase
      uses: actions/checkout@v3
      with:
          path: ./oku
    - name: Checkout GitHub Pages environment
      uses: actions/checkout@v3
      with:
          ref: gh-pages
          path: ./gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate documentation
      run: |
          sudo apt-get -qq install tree > /dev/null
          printf "Codebase:\n" && tree ./oku
          rm -rf ./gh-pages/code/
          
          cd ./oku
          printf "\nGenerating documentation … "
          time cargo doc --no-deps --document-private-items --release --quiet
          cd ../
          
          mkdir -p ./gh-pages/code
          cp -ar ./oku/target/doc/* ./gh-pages/code
          printf "\nDocumentation:\n" && tree ./gh-pages/code
    - name: Publish
      run: |
          cd ./gh-pages
          git config --global user.name 'Oku'
          git config --global user.email 'Dirout@users.noreply.github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -am "Publish documentation to GitHub Pages"
          git push
