on: [push]

name: 'Build: macOS (ARM64)'

jobs:
  mac_aarch64:
    name: macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install development dependencies
        run: |
          brew install gtk+3 libsoup libpsl icu4c
          brew link icu4c --force
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          default: true
          profile: minimal
      - name: Build Oku
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target aarch64-apple-darwin
      - name: Prepare Oku for upload
        run: |
          cd ./target/aarch64-apple-darwin/release/
          strip ./oku
          chmod +x ./oku
          tar -cvf aarch64-oku.osx.tar \
          oku
      - name: Upload Oku build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-oku.osx
          path: ./target/aarch64-apple-darwin/release/aarch64-oku.osx.tar
          if-no-files-found: error
