name: Dependency security audit (scheduled)
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scheduled_security_audit:
    name: Security audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}